# Generated by Django 5.1.1 on 2024-10-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('usagerate', models.CharField(max_length=10)),
                ('killrate_onekill', models.IntegerField()),
                ('killrate_twokills', models.IntegerField()),
                ('killrate_threekills', models.IntegerField()),
                ('killrate_fourkills', models.IntegerField()),
                ('perks', models.JSONField()),
                ('imagenUrl', models.URLField()),
                ('power', models.CharField(max_length=100)),
                ('powerdescription', models.TextField()),
                ('speedmove', models.CharField(max_length=10)),
                ('high', models.CharField(max_length=50)),
                ('terrorradio', models.CharField(max_length=10)),
                ('dlc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadAsesino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('usagerate', models.CharField(max_length=10)),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadSuperviviente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('usagerate', models.CharField(max_length=10)),
                ('perks', models.JSONField()),
                ('imagenUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Superviviente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('perks', models.JSONField()),
                ('imagenUrl', models.URLField()),
                ('dlc', models.CharField(max_length=100)),
            ],
        ),
    ]
