# Generated by Django 5.1.1 on 2024-10-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelosyrutas', '0002_alter_asesino_speedmove_alter_asesino_terrorradio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesino',
            name='dlc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asesino',
            name='high',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asesino',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asesino',
            name='power',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asesino',
            name='speedmove',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asesino',
            name='terrorradio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asesino',
            name='usagerate',
            field=models.CharField(max_length=200),
        ),
    ]
