# Generated by Django 5.1.1 on 2024-10-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelosyrutas', '0004_alter_asesino_id_alter_superviviente_dlc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superviviente',
            old_name='imagenUrl',
            new_name='imageUrl',
        ),
    ]
