# Generated by Django 5.1.1 on 2024-11-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelosyrutas', '0008_rename_imagenurl_habilidadsuperviviente_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('ban_status', models.BooleanField(default=False)),
                ('comentaries', models.CharField(blank=True, max_length=2000, null=True)),
                ('usertype', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=200)),
            ],
        ),
    ]
